### PR TITLE
Updated code and README to run with Debezium 2.7

### PR DESCRIPTION
**Pull request by AlessandroLollo**
Hey there 👋 

This PR refactor scripts and README to work with Debezium 2.7.

### CODE REVIEW

**Comment by AlessandroLollo** [comment]
@microsoft-github-policy-service agree

**Comment by yorek** [comment]
Let me know what the PR is ready to be merged

**Comment by AlessandroLollo** [comment]
> Let me know what the PR is ready to be merged

Need some time to test changes to both bash and PS scripts.
Will give you a heads up once I'm confident everything is working fine!

**Comment by AlessandroLollo** [comment]
Hey @yorek 👋 
I've tested the demo end to end, I'm fairly confident the PR can be merged!

**Comment by yorek** [comment]
Fantastic, merging it now :)

**Comment by yorek** [comment]
Done, thanks a lot for your contribution!

**Pull request merged**
